/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearbookRouteImport } from './routes/yearbook'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LanguageClubRouteImport } from './routes/language-club'
import { Route as InternationalAffairsRouteImport } from './routes/international-affairs'
import { Route as InstructorRegistrationRouteImport } from './routes/instructor-registration'
import { Route as HeadTeacherMessageRouteImport } from './routes/head-teacher-message'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FounderMessageRouteImport } from './routes/founder-message'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as EnglishCoursesRouteImport } from './routes/english-courses'
import { Route as EcaClubsRouteImport } from './routes/eca-clubs'
import { Route as CounselingRouteImport } from './routes/counseling'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChairmansMessageRouteImport } from './routes/chairmans-message'
import { Route as CareerRouteImport } from './routes/career'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as BulletinRouteImport } from './routes/bulletin'
import { Route as BoardOfDirectorsRouteImport } from './routes/board-of-directors'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AlumniRouteImport } from './routes/alumni'
import { Route as AdvisorsRouteImport } from './routes/advisors'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AcademicCalendarRouteImport } from './routes/academic-calendar'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FacultyIndexRouteImport } from './routes/faculty.index'
import { Route as AcademicsIndexRouteImport } from './routes/academics.index'
import { Route as GallerySlugRouteImport } from './routes/gallery.$slug'
import { Route as FacultyIdRouteImport } from './routes/faculty.$id'
import { Route as CounselingTypeRouteImport } from './routes/counseling.$type'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AcademicsNewsRouteImport } from './routes/academics.news'
import { Route as AcademicsNewsSlugRouteImport } from './routes/academics.news.$slug'

const YearbookRoute = YearbookRouteImport.update({
  id: '/yearbook',
  path: '/yearbook',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageClubRoute = LanguageClubRouteImport.update({
  id: '/language-club',
  path: '/language-club',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalAffairsRoute = InternationalAffairsRouteImport.update({
  id: '/international-affairs',
  path: '/international-affairs',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRegistrationRoute = InstructorRegistrationRouteImport.update({
  id: '/instructor-registration',
  path: '/instructor-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadTeacherMessageRoute = HeadTeacherMessageRouteImport.update({
  id: '/head-teacher-message',
  path: '/head-teacher-message',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FounderMessageRoute = FounderMessageRouteImport.update({
  id: '/founder-message',
  path: '/founder-message',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishCoursesRoute = EnglishCoursesRouteImport.update({
  id: '/english-courses',
  path: '/english-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const EcaClubsRoute = EcaClubsRouteImport.update({
  id: '/eca-clubs',
  path: '/eca-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CounselingRoute = CounselingRouteImport.update({
  id: '/counseling',
  path: '/counseling',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChairmansMessageRoute = ChairmansMessageRouteImport.update({
  id: '/chairmans-message',
  path: '/chairmans-message',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const BulletinRoute = BulletinRouteImport.update({
  id: '/bulletin',
  path: '/bulletin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardOfDirectorsRoute = BoardOfDirectorsRouteImport.update({
  id: '/board-of-directors',
  path: '/board-of-directors',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRoute = AlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorsRoute = AdvisorsRouteImport.update({
  id: '/advisors',
  path: '/advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCalendarRoute = AcademicCalendarRouteImport.update({
  id: '/academic-calendar',
  path: '/academic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyIndexRoute = FacultyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyRoute,
} as any)
const AcademicsIndexRoute = AcademicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademicsRoute,
} as any)
const GallerySlugRoute = GallerySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GalleryRoute,
} as any)
const FacultyIdRoute = FacultyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FacultyRoute,
} as any)
const CounselingTypeRoute = CounselingTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => CounselingRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AcademicsNewsRoute = AcademicsNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsNewsSlugRoute = AcademicsNewsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AcademicsNewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academics': typeof AcademicsRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/advisors': typeof AdvisorsRoute
  '/alumni': typeof AlumniRoute
  '/blog': typeof BlogRouteWithChildren
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/bulletin': typeof BulletinRoute
  '/campus': typeof CampusRoute
  '/career': typeof CareerRoute
  '/chairmans-message': typeof ChairmansMessageRoute
  '/contact': typeof ContactRoute
  '/counseling': typeof CounselingRouteWithChildren
  '/eca-clubs': typeof EcaClubsRoute
  '/english-courses': typeof EnglishCoursesRoute
  '/facilities': typeof FacilitiesRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/fees': typeof FeesRoute
  '/founder-message': typeof FounderMessageRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/head-teacher-message': typeof HeadTeacherMessageRoute
  '/instructor-registration': typeof InstructorRegistrationRoute
  '/international-affairs': typeof InternationalAffairsRoute
  '/language-club': typeof LanguageClubRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yearbook': typeof YearbookRoute
  '/academics/news': typeof AcademicsNewsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/counseling/$type': typeof CounselingTypeRoute
  '/faculty/$id': typeof FacultyIdRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/academics/': typeof AcademicsIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/academics/news/$slug': typeof AcademicsNewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/admissions': typeof AdmissionsRoute
  '/advisors': typeof AdvisorsRoute
  '/alumni': typeof AlumniRoute
  '/blog': typeof BlogRouteWithChildren
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/bulletin': typeof BulletinRoute
  '/campus': typeof CampusRoute
  '/career': typeof CareerRoute
  '/chairmans-message': typeof ChairmansMessageRoute
  '/contact': typeof ContactRoute
  '/counseling': typeof CounselingRouteWithChildren
  '/eca-clubs': typeof EcaClubsRoute
  '/english-courses': typeof EnglishCoursesRoute
  '/facilities': typeof FacilitiesRoute
  '/fees': typeof FeesRoute
  '/founder-message': typeof FounderMessageRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/head-teacher-message': typeof HeadTeacherMessageRoute
  '/instructor-registration': typeof InstructorRegistrationRoute
  '/international-affairs': typeof InternationalAffairsRoute
  '/language-club': typeof LanguageClubRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yearbook': typeof YearbookRoute
  '/academics/news': typeof AcademicsNewsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/counseling/$type': typeof CounselingTypeRoute
  '/faculty/$id': typeof FacultyIdRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/academics': typeof AcademicsIndexRoute
  '/faculty': typeof FacultyIndexRoute
  '/academics/news/$slug': typeof AcademicsNewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/academics': typeof AcademicsRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/advisors': typeof AdvisorsRoute
  '/alumni': typeof AlumniRoute
  '/blog': typeof BlogRouteWithChildren
  '/board-of-directors': typeof BoardOfDirectorsRoute
  '/bulletin': typeof BulletinRoute
  '/campus': typeof CampusRoute
  '/career': typeof CareerRoute
  '/chairmans-message': typeof ChairmansMessageRoute
  '/contact': typeof ContactRoute
  '/counseling': typeof CounselingRouteWithChildren
  '/eca-clubs': typeof EcaClubsRoute
  '/english-courses': typeof EnglishCoursesRoute
  '/facilities': typeof FacilitiesRoute
  '/faculty': typeof FacultyRouteWithChildren
  '/fees': typeof FeesRoute
  '/founder-message': typeof FounderMessageRoute
  '/gallery': typeof GalleryRouteWithChildren
  '/head-teacher-message': typeof HeadTeacherMessageRoute
  '/instructor-registration': typeof InstructorRegistrationRoute
  '/international-affairs': typeof InternationalAffairsRoute
  '/language-club': typeof LanguageClubRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yearbook': typeof YearbookRoute
  '/academics/news': typeof AcademicsNewsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/counseling/$type': typeof CounselingTypeRoute
  '/faculty/$id': typeof FacultyIdRoute
  '/gallery/$slug': typeof GallerySlugRoute
  '/academics/': typeof AcademicsIndexRoute
  '/faculty/': typeof FacultyIndexRoute
  '/academics/news/$slug': typeof AcademicsNewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic-calendar'
    | '/academics'
    | '/admissions'
    | '/advisors'
    | '/alumni'
    | '/blog'
    | '/board-of-directors'
    | '/bulletin'
    | '/campus'
    | '/career'
    | '/chairmans-message'
    | '/contact'
    | '/counseling'
    | '/eca-clubs'
    | '/english-courses'
    | '/facilities'
    | '/faculty'
    | '/fees'
    | '/founder-message'
    | '/gallery'
    | '/head-teacher-message'
    | '/instructor-registration'
    | '/international-affairs'
    | '/language-club'
    | '/projects'
    | '/sitemap.xml'
    | '/yearbook'
    | '/academics/news'
    | '/blog/$slug'
    | '/counseling/$type'
    | '/faculty/$id'
    | '/gallery/$slug'
    | '/academics/'
    | '/faculty/'
    | '/academics/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic-calendar'
    | '/admissions'
    | '/advisors'
    | '/alumni'
    | '/blog'
    | '/board-of-directors'
    | '/bulletin'
    | '/campus'
    | '/career'
    | '/chairmans-message'
    | '/contact'
    | '/counseling'
    | '/eca-clubs'
    | '/english-courses'
    | '/facilities'
    | '/fees'
    | '/founder-message'
    | '/gallery'
    | '/head-teacher-message'
    | '/instructor-registration'
    | '/international-affairs'
    | '/language-club'
    | '/projects'
    | '/sitemap.xml'
    | '/yearbook'
    | '/academics/news'
    | '/blog/$slug'
    | '/counseling/$type'
    | '/faculty/$id'
    | '/gallery/$slug'
    | '/academics'
    | '/faculty'
    | '/academics/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic-calendar'
    | '/academics'
    | '/admissions'
    | '/advisors'
    | '/alumni'
    | '/blog'
    | '/board-of-directors'
    | '/bulletin'
    | '/campus'
    | '/career'
    | '/chairmans-message'
    | '/contact'
    | '/counseling'
    | '/eca-clubs'
    | '/english-courses'
    | '/facilities'
    | '/faculty'
    | '/fees'
    | '/founder-message'
    | '/gallery'
    | '/head-teacher-message'
    | '/instructor-registration'
    | '/international-affairs'
    | '/language-club'
    | '/projects'
    | '/sitemap.xml'
    | '/yearbook'
    | '/academics/news'
    | '/blog/$slug'
    | '/counseling/$type'
    | '/faculty/$id'
    | '/gallery/$slug'
    | '/academics/'
    | '/faculty/'
    | '/academics/news/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicCalendarRoute: typeof AcademicCalendarRoute
  AcademicsRoute: typeof AcademicsRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRoute
  AdvisorsRoute: typeof AdvisorsRoute
  AlumniRoute: typeof AlumniRoute
  BlogRoute: typeof BlogRouteWithChildren
  BoardOfDirectorsRoute: typeof BoardOfDirectorsRoute
  BulletinRoute: typeof BulletinRoute
  CampusRoute: typeof CampusRoute
  CareerRoute: typeof CareerRoute
  ChairmansMessageRoute: typeof ChairmansMessageRoute
  ContactRoute: typeof ContactRoute
  CounselingRoute: typeof CounselingRouteWithChildren
  EcaClubsRoute: typeof EcaClubsRoute
  EnglishCoursesRoute: typeof EnglishCoursesRoute
  FacilitiesRoute: typeof FacilitiesRoute
  FacultyRoute: typeof FacultyRouteWithChildren
  FeesRoute: typeof FeesRoute
  FounderMessageRoute: typeof FounderMessageRoute
  GalleryRoute: typeof GalleryRouteWithChildren
  HeadTeacherMessageRoute: typeof HeadTeacherMessageRoute
  InstructorRegistrationRoute: typeof InstructorRegistrationRoute
  InternationalAffairsRoute: typeof InternationalAffairsRoute
  LanguageClubRoute: typeof LanguageClubRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YearbookRoute: typeof YearbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yearbook': {
      id: '/yearbook'
      path: '/yearbook'
      fullPath: '/yearbook'
      preLoaderRoute: typeof YearbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language-club': {
      id: '/language-club'
      path: '/language-club'
      fullPath: '/language-club'
      preLoaderRoute: typeof LanguageClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-affairs': {
      id: '/international-affairs'
      path: '/international-affairs'
      fullPath: '/international-affairs'
      preLoaderRoute: typeof InternationalAffairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor-registration': {
      id: '/instructor-registration'
      path: '/instructor-registration'
      fullPath: '/instructor-registration'
      preLoaderRoute: typeof InstructorRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/head-teacher-message': {
      id: '/head-teacher-message'
      path: '/head-teacher-message'
      fullPath: '/head-teacher-message'
      preLoaderRoute: typeof HeadTeacherMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founder-message': {
      id: '/founder-message'
      path: '/founder-message'
      fullPath: '/founder-message'
      preLoaderRoute: typeof FounderMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english-courses': {
      id: '/english-courses'
      path: '/english-courses'
      fullPath: '/english-courses'
      preLoaderRoute: typeof EnglishCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eca-clubs': {
      id: '/eca-clubs'
      path: '/eca-clubs'
      fullPath: '/eca-clubs'
      preLoaderRoute: typeof EcaClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counseling': {
      id: '/counseling'
      path: '/counseling'
      fullPath: '/counseling'
      preLoaderRoute: typeof CounselingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chairmans-message': {
      id: '/chairmans-message'
      path: '/chairmans-message'
      fullPath: '/chairmans-message'
      preLoaderRoute: typeof ChairmansMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulletin': {
      id: '/bulletin'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof BulletinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board-of-directors': {
      id: '/board-of-directors'
      path: '/board-of-directors'
      fullPath: '/board-of-directors'
      preLoaderRoute: typeof BoardOfDirectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni': {
      id: '/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisors': {
      id: '/advisors'
      path: '/advisors'
      fullPath: '/advisors'
      preLoaderRoute: typeof AdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-calendar': {
      id: '/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof AcademicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty/': {
      id: '/faculty/'
      path: '/'
      fullPath: '/faculty/'
      preLoaderRoute: typeof FacultyIndexRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/academics/': {
      id: '/academics/'
      path: '/'
      fullPath: '/academics/'
      preLoaderRoute: typeof AcademicsIndexRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/gallery/$slug': {
      id: '/gallery/$slug'
      path: '/$slug'
      fullPath: '/gallery/$slug'
      preLoaderRoute: typeof GallerySlugRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/faculty/$id': {
      id: '/faculty/$id'
      path: '/$id'
      fullPath: '/faculty/$id'
      preLoaderRoute: typeof FacultyIdRouteImport
      parentRoute: typeof FacultyRoute
    }
    '/counseling/$type': {
      id: '/counseling/$type'
      path: '/$type'
      fullPath: '/counseling/$type'
      preLoaderRoute: typeof CounselingTypeRouteImport
      parentRoute: typeof CounselingRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/academics/news': {
      id: '/academics/news'
      path: '/news'
      fullPath: '/academics/news'
      preLoaderRoute: typeof AcademicsNewsRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/news/$slug': {
      id: '/academics/news/$slug'
      path: '/$slug'
      fullPath: '/academics/news/$slug'
      preLoaderRoute: typeof AcademicsNewsSlugRouteImport
      parentRoute: typeof AcademicsNewsRoute
    }
  }
}

interface AcademicsNewsRouteChildren {
  AcademicsNewsSlugRoute: typeof AcademicsNewsSlugRoute
}

const AcademicsNewsRouteChildren: AcademicsNewsRouteChildren = {
  AcademicsNewsSlugRoute: AcademicsNewsSlugRoute,
}

const AcademicsNewsRouteWithChildren = AcademicsNewsRoute._addFileChildren(
  AcademicsNewsRouteChildren,
)

interface AcademicsRouteChildren {
  AcademicsNewsRoute: typeof AcademicsNewsRouteWithChildren
  AcademicsIndexRoute: typeof AcademicsIndexRoute
}

const AcademicsRouteChildren: AcademicsRouteChildren = {
  AcademicsNewsRoute: AcademicsNewsRouteWithChildren,
  AcademicsIndexRoute: AcademicsIndexRoute,
}

const AcademicsRouteWithChildren = AcademicsRoute._addFileChildren(
  AcademicsRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CounselingRouteChildren {
  CounselingTypeRoute: typeof CounselingTypeRoute
}

const CounselingRouteChildren: CounselingRouteChildren = {
  CounselingTypeRoute: CounselingTypeRoute,
}

const CounselingRouteWithChildren = CounselingRoute._addFileChildren(
  CounselingRouteChildren,
)

interface FacultyRouteChildren {
  FacultyIdRoute: typeof FacultyIdRoute
  FacultyIndexRoute: typeof FacultyIndexRoute
}

const FacultyRouteChildren: FacultyRouteChildren = {
  FacultyIdRoute: FacultyIdRoute,
  FacultyIndexRoute: FacultyIndexRoute,
}

const FacultyRouteWithChildren =
  FacultyRoute._addFileChildren(FacultyRouteChildren)

interface GalleryRouteChildren {
  GallerySlugRoute: typeof GallerySlugRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GallerySlugRoute: GallerySlugRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicCalendarRoute: AcademicCalendarRoute,
  AcademicsRoute: AcademicsRouteWithChildren,
  AdmissionsRoute: AdmissionsRoute,
  AdvisorsRoute: AdvisorsRoute,
  AlumniRoute: AlumniRoute,
  BlogRoute: BlogRouteWithChildren,
  BoardOfDirectorsRoute: BoardOfDirectorsRoute,
  BulletinRoute: BulletinRoute,
  CampusRoute: CampusRoute,
  CareerRoute: CareerRoute,
  ChairmansMessageRoute: ChairmansMessageRoute,
  ContactRoute: ContactRoute,
  CounselingRoute: CounselingRouteWithChildren,
  EcaClubsRoute: EcaClubsRoute,
  EnglishCoursesRoute: EnglishCoursesRoute,
  FacilitiesRoute: FacilitiesRoute,
  FacultyRoute: FacultyRouteWithChildren,
  FeesRoute: FeesRoute,
  FounderMessageRoute: FounderMessageRoute,
  GalleryRoute: GalleryRouteWithChildren,
  HeadTeacherMessageRoute: HeadTeacherMessageRoute,
  InstructorRegistrationRoute: InstructorRegistrationRoute,
  InternationalAffairsRoute: InternationalAffairsRoute,
  LanguageClubRoute: LanguageClubRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YearbookRoute: YearbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
